<a href="https://colab.research.google.com/github/MuhammadAbdullah083/AI-engineering-journey/blob/main/day_7_Libraries%2CPip%2CNumpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#NumPy Arrays vs Python Lists
my_list = [1, 2, 3, 4, 5]

# NumPy array
import numpy as np
my_array = np.array([1, 2, 3, 4, 5])

print(type(my_list))   # <class 'list'>
print(type(my_array))  # <class 'numpy.ndarray'>

<class 'list'>
<class 'numpy.ndarray'>


In [ ]:
#vectorization
import numpy as np
array1=np.array([1,3,4,5])
array2=np.array([3,4,5,6])
print(array1+array2)
print(array1*array2)
print(array1/array2)

[ 4  7  9 11]
[ 3 12 20 30]
[0.33333333 0.75       0.8        0.83333333]


In [1]:
#Creating Arrays
import numpy as np
a = np.array([1, 2, 3, 4, 5])
zeros=np.zeros([0,0,0,0,0])
ones=np.ones([1,1,1,1,1])

print(a)
print(zeros)
print(ones)

[1 2 3 4 5]
[]
[[[[[1.]]]]]


In [2]:
import numpy as np
my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)
print(my_array)
print(type)

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
import numpy as np
scores=np.array([55,60,75,80,90]) # Convert to a NumPy array
print(scores+5)
print(scores*2)
print(scores/2)

print(np.min(scores))
print(np.max(scores))
print(np.mean(scores))
print(np.median(scores))
print(np.std(scores))


[60 65 80 85 95]
[110 120 150 160 180]
[27.5 30.  37.5 40.  45. ]
55
90
72.0
75.0
12.884098726725126


In [3]:
import numpy as np
matrix=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]

])
print(matrix.shape)
print(matrix.size)
print(matrix.ndim)
print(matrix[0])
print(matrix[1][2])


(3, 3)
9
2
[1 2 3]
6


In [1]:
import numpy as np

np.zeros(5)             # [0. 0. 0. 0. 0.]
np.ones(5)              # [1. 1. 1. 1. 1.]
np.arange(0, 10, 2)     # [0 2 4 6 8] — like range() but numpy
np.linspace(0, 1, 5)    # [0.   0.25 0.5  0.75 1. ] — 5 evenly spaced numbers
np.random.randint(1, 10, size=5)  # 5 random integers between 1 and 9

array([9, 2, 4, 2, 4])

In [2]:
import numpy as np
marks = np.array([55, 60, 75, 80, 90,100])

print("marks",marks)
print("Average",np.mean(marks))
print("Median",np.median(marks))
print("Standard Deviation",np.std(marks))
print("Above 80",marks[marks>80])

marks [ 55  60  75  80  90 100]
Average 76.66666666666667
Median 77.5
Standard Deviation 15.723301886761007
Above 80 [ 90 100]


In [3]:
import numpy as np

students = np.array([45, 67, 89, 23, 78, 95, 56, 88, 72, 61])

print("Mean:", np.mean(students))
print("Median:", np.median(students))
print("Std:", np.std(students))
print("Passed (above 50):", students[students > 50])
print("Total passed:", len(students[students > 50]))

Mean: 67.4
Median: 69.5
Std: 21.04851538707659
Passed (above 50): [67 89 78 95 56 88 72 61]
Total passed: 8
